### PR TITLE
Workflow for auto-creating keys based on aa/oh/ch visemes

### PR DESCRIPTION
**Pull request by feilen**
Here's the workflow I was describing. It looks like my git may have tried to tackle whitespaces, so it may be a little harder to read what's changed.

This will take care of almost all the keys you need, or at least give you a fairly adequate starting point.

Future work:
- Currently transforms are done in local coordinates, meaning rotations have to be applied to get the expected results.
- I think there should be a way to get Mouth_Lower_Overlay and Mouth_Ape_Shape without too much trouble.
- CheekPuffL/R and CheekSuck should be derivable from a single CheekPuff key.
- Dilation/Constriction would be easy to add, assuming you have pupil keys already (rexes, awtters do)
- __some__ kind of tongue handling would cover a lot of ground.

Squeeze:
image
Blink:
image
Wide:
image
UpperUpRight:
image
LowerDownLeft:
image
JawOpen:
image
MouthSadLeft:
image
MouthUpperLeft:
image
JawLeft:
image
JawForward:
image
UI update (disables toggles to show you which are being handled by visemes):
image

> Based on the assumption that CH generally moves the upper lip more than
> OH, it's possible to automatically detect which vertices belong to the
> upper and lower lips. With that, and the assumption that CH only moves
> the lips (which is generally correct):
> 
> - Mouth{Upper/Lower}{Up/Down}{Left/Right} can be created by mixing CH on the upper/
> lower lips, doing some linear interpolation in the middle to avoid a
> harsh falloff.
> - Mouth{Upper/Lower}{Left/Right} can be created by applying the magnitude
> of the CH key's movement directly left/right
> - MouthPout can be created as above, but forward and applying to both lips
> - Mouth{Upper/Lower}Inside can be created as above, but moving the lips
> inward
> - Jaw{Left/Right/Forward} can be similarly created from the magnitude of
> AA
> - JawOpen can be created from AA * 2.0 (this seems to match references on
> most models)
> 
> In addition, most models already have a 'blink', 'smile', and 'sad' key.
> - for smile/sad, we just do the left/right split as before
> - for blink, by doing a split and applying it 1.0x, 1.1x and -0.15x,
>   we can populate the 'Blink', 'Squeeze' and 'Wide' keys respectively
>   (or at least give a good starting point)
> 
> Once all of these are populated, all that remains left to do are the
> Cheek*/Tongue*/Eye{UpDownLeftRight} keys, Mouth_Lower_Overlay/Ape_Shape
> (which I suspect could be approximated), and pupil dilation/restriction.
> Plus whatever inevitable cleanup you need.

### CODE REVIEW

**Comment by Adjerry91** [comment]
I currently have beta branch with new features need to figure out how to merge this to my beta branch.

**Comment by feilen** [comment]
Ahhh I should have realized. I don't think you can do it from Github. I'll rebase, close this PR and open a new one when I get a minute

**Comment by Adjerry91** [comment]
Give me tomorrow to clean up the beta branch, I just did not merge it yet because it is experimental remapping of visemes and enable disable functionality on the shapekey creation. Also I am going to remove the VRC tag for face tracking as this tool is generalized for any face tracking.

**Comment by feilen** [comment]
Ah heck, didn't see your message there. Feel free to cleanup as-needed, I'll re-rebase the changes whenever you're ready

**Pull request closed without merging**
